### PR TITLE
OPENMETA-748 Terminate background Creo process when CAD import progress dialog cancel button is clicked

### PR DESCRIPTION
**Pull request by jonathonw**
This prevents a GME crash when we try to write that background process's stdout/stderr to the GME console.

Doing this as a PR because I'm not sure if there's a reason why this process wasn't being cleaned up--  are there side effects to killing Creo?  (like not cleaning up checked out licenses, maybe?)

### CODE REVIEW

**Comment by ksmyth** [comment]
Right, the license won't be released if we kill the process. Though we'd also have this issue if the user immediately closes GME since the job object will be closed.

What about just checking a cancelled flag in the stdout/stderr handler?

**Comment by jonathonw** [comment]
I can do that (or I can unregister the handler, or tell it to stop reading the output streams entirely), but... if we can’t safely cancel the long-running operation here (the actual CAD component creation in GME happens trivially quickly, and after the dialog disappears), should there be a cancel button at all?  Yes, it frees up GME to do other things, but it leaves Creo running in the background burning CPU cycles on nothing.

**Comment by ksmyth** [comment]
Since we can’t cancel the Creo, those cycles are going to be burned. Isn’t the cancel button strictly an improvement, then?

**Comment by jonathonw** [comment]
Updated to check a cancelled flag in the stdout/stderr handler--  how's this look?

**Pull request merged**
